# Generated by Django 3.1.4 on 2021-05-29 15:24

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddInstitute',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name=django.db.models.fields.related.ForeignKey)),
            ],
        ),
    ]
