# Generated by Django 3.1.4 on 2021-05-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addinstitute',
            old_name='name',
            new_name='int_name',
        ),
    ]
