# Generated by Django 3.1.4 on 2021-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210529_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinstitute',
            name='int_name',
            field=models.CharField(max_length=200),
        ),
    ]
