# Generated by Django 3.1.4 on 2021-05-29 15:40

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210529_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinstitute',
            name='int_site',
            field=models.CharField(default='www.site.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='addinstitute',
            name='int_name',
            field=models.CharField(max_length=200, verbose_name=django.db.models.fields.related.ForeignKey),
        ),
    ]
