# Generated by Django 3.1.4 on 2021-05-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210529_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinstitute',
            name='int_name',
            field=models.CharField(max_length=100),
        ),
    ]
