# Generated by Django 3.1.6 on 2021-06-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_surveymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveymodel',
            old_name='srvy_desp',
            new_name='srvy_desc',
        ),
    ]
