# Generated by Django 3.2.3 on 2021-07-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210630_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='srvy_desc',
            field=models.TextField(),
        ),
    ]
